FROM python:3.10-slim-bullseye

ENV PYTHONUNBUFFERED True

WORKDIR /app.dev

RUN apt-get update -y && apt-get install -y \
    git

COPY pyproject.toml poetry.lock* ./

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install